#!/bin/env python

import sys
import CS
from   CS import *

def main():

    commands = ['db','lsf','coral','coral_lsf_jobs']

    if len(sys.argv)<=1:
        print
        print 'Run different COMPASS-SOFT related scripts'
        print 'USAGE:                      $ cs <command> [arguments]'
        print 'For more information type:  $ cs <command> --help'
        print 'List of commands:           %s' % ','.join(commands)
        print
        return 1
    

    if sys.argv[1] not in commands:
        print 'Unknown command: %s' % sys.argv[1]
        print 'Known commands are: %s' % ' '.join(commands)
        return 1

    # First argument is not needed.
    del sys.argv[0]

    return getattr(CS,sys.argv[0]).main()

if __name__=='__main__':
    sys.exit(main())
