#!/bin/env python

import sys,optparse

if __name__=='__main__':

    #parser = optparse.OptionParser()

    #(options, args) = parser.parse_args()

    print sys.argv

    if sys.argv[1]=='coral':
        import coral
        del sys.argv[1]
        sys.argv[0] += ' coral'
        coral.main()
