SET( CLHEP_ROOT_DIR $ENV{CLHEP} )

IF( "${CLHEP_ROOT_DIR}" STREQUAL "" )
    MESSAGE(FATAL_ERROR "CLHEP environment variable is not set!")
ELSE( "${CLHEP_ROOT_DIR}" STREQUAL "" )
    SET(CLHEP_INCLUDE_DIR ${CLHEP_ROOT_DIR}/include)
    SET(CLHEP_LIBRARIES_DIR "-L${CLHEP_ROOT_DIR}/lib -lCLHEP")
ENDIF( "${CLHEP_ROOT_DIR}" STREQUAL "" )
