FIND_PROGRAM(ROOT_CONFIG root-config)
IF( ${ROOT_CONFIG} STREQUAL "ROOT_CONFIG-NOTFOUND" )
    #SET(ROOT_FOUND "NO")
    MESSAGE(FATAL_ERROR "ROOT program 'root-config' is not found!")
ENDIF( ${ROOT_CONFIG} STREQUAL "ROOT_CONFIG-NOTFOUND" )

EXEC_PROGRAM(${ROOT_CONFIG}
             ARGS --incdir
             OUTPUT_VARIABLE ROOT_INCLUDE_DIR)

EXEC_PROGRAM(${ROOT_CONFIG}
             ARGS --glibs
             OUTPUT_VARIABLE ROOT_LIBRARIES)

EXEC_PROGRAM(${ROOT_CONFIG}
             ARGS --libdir
             OUTPUT_VARIABLE ROOT_LIBRARY_DIR)
